const gregorianToHebDay = (hebDay) => {
  switch (hebDay) {
    case `א'`:
    case `א`:
      return '1';
    case `ב'`:
    case `ב`:
      return '2';
    case `ג'`:
    case `ג`:
      return '3';
    case `ד'`:
    case `ד`:
      return '4';
    case `ה'`:
    case `ה`:
      return '5';
    case `ו'`:
    case `ו`:
      return '6';
    case `ז'`:
    case `ז`:
      return '7';
    case `ח'`:
    case `ח`:
      return '8';
    case `ט'`:
    case `ט`:
      return '9';
    case `י'`:
    case `י`:
      return '10';
    case `יא'`:
    case `יא`:
    case `י"א`:
    case `י״א`:
      return '11';
    case `יב'`:
    case `יב`:
    case `י"ב`:
    case `י״ב`:
      return '12';
    case `יג'`:
    case `יג`:
    case `י"ג`:
    case `י״ג`:
      return '13';
    case `יד'`:
    case `יד`:
    case `י"ד`:
    case `י״ד`:
      return '14';
    case `טו'`:
    case `טו`:
    case `ט"ו`:
    case `ט״ו`:
      return '15';
    case `טז'`:
    case `טז`:
    case `ט"ז`:
    case `ט״ז`:
      return '16';
    case `יז'`:
    case `יז`:
    case `י"ז`:
    case `י״ז`:
      return '17';
    case `יח'`:
    case `יח`:
    case `י"ח`:
    case `י״ח`:
      return '18';
    case `יט'`:
    case `יט`:
    case `י"ט`:
    case `י״ט`:
      return '19';
    case `כ'`:
    case `כ`:
      return '20';
    case `כא'`:
    case `כא`:
    case `כ"א`:
    case `כ״א`:
      return '21';
    case `כב'`:
    case `כב`:
    case `כ"ב`:
    case `כ״ב`:
      return '22';
    case `כג'`:
    case `כג`:
    case `כ"ג`:
    case `כ״ג`:
      return '23';
    case `כד'`:
    case `כד`:
    case `כ"ד`:
    case `כ״ד`:
      return '24';
    case `כה'`:
    case `כה`:
    case `כ"ה`:
    case `כ״ה`:
      return '25';
    case `כו'`:
    case `כו`:
    case `כ"ו`:
    case `כ״ו`:
      return '26';
    case `כז'`:
    case `כז`:
    case `כ"ז`:
    case `כ״ז`:
      return '27';
    case `כח'`:
    case `כח`:
    case `כ"ח`:
    case `כ״ח`:
      return '28';
    case `כט'`:
    case `כט`:
    case `כ"ט`:
    case `כ״ט`:
      return '29';
    case `ל'`:
    case `ל`:
      return '30';
    case `לא'`:
    case `לא`:
    case `ל"א`:
    case `ל״א`:
      return '31';
    case `לב'`:
    case `לב`:
    case `ל"ב`:
    case `ל״ב`:
      return '32';
    case `לג'`:
    case `לג`:
    case `ל"ג`:
    case `ל״ג`:
      return '33';
    default:
      return null;
  }
};
const gregorianToHebMonth = (hebMonth) => {
  switch (hebMonth) {
    case `תשרי`:
      return 'tishrei';
    case `חשון`:
    case `חשוון`:
      return 'cheshvan';
    case `כסלו`:
      return 'kislev';
    case `טבת`:
      return 'tevet';
    case `שבט`:
      return 'shevt';
    case `אדר`:
      return 'adar';
    case `ניסן`:
      return 'nisan';
    case `אייר`:
      return 'iyar';
    case `סיון`:
      return 'sivan';
    case `תמוז`:
      return 'tammuz';
    case `אב`:
      return 'av';
    case `אלול`:
      return 'elul';
    default:
      return null;
  }
};
export { gregorianToHebMonth, gregorianToHebDay };
