name: QA CI/CD

on:
  push:
    branches:
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy to QA
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
            cd /var/www/qa.lifecloud-qr.com
            git pull origin QA --allow-unrelated-histories
            cd /var/www/qa.lifecloud-qr.com/server
            npm install
            pm2 restart all --update-env
            cd /var/www/qa.lifecloud-qr.com/client
            npm install && npm run build
            chown -R www-data:www-data /var/www/qa.lifecloud-qr.com/client/build
            service nginx restart
